<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Title>Stravaig Monotonic Clock</Title>
    <PackageTags>clock time monotonic</PackageTags>
    <ImplicitUsings>disable</ImplicitUsings>
    <Description>A monotonic clock for time measurement.

    Built on $(StravaigBuildTime).
    Build run details at: $(StravaigWorkflowUrl)
    Release notes at: $(StravaigReleaseNotes)
    </Description>
  </PropertyGroup>

  <ItemGroup>
    <None Include="stravaig-icon.png" Pack="true" PackagePath="/" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <PackageReference Include="Microsoft.Bcl.TimeProvider" Version="10.0.11" />
  </ItemGroup>

</Project>
