remote_theme: Stravaig-Projects/stravaig-theme
plugins:
  - jekyll-remote-theme 
  - jekyll-relative-links

exclude:
  - scripts

title: Stravaig Monotonic Clock
description: A monotonic clock abstraction for elapsed-time measurement.

kramdown:
    highlighter: rouge
    syntax_highlighter_opts:
        block:
            line_numbers: true

github:
  repository_url: https://github.com/Stravaig-Projects/Stravaig.MonotonicClock

nuget:
  urls:
    - https://www.nuget.org/packages/Stravaig.MonotonicClock