<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Title>Stravaig Monotonic Clock - Dependency Injection</Title>
        <PackageTags>clock time monotonic dependency-injection di</PackageTags>
        <ImplicitUsings>disable</ImplicitUsings>
        <Description>Dependency injection extensions for registering the Stravaig monotonic clock as a TimeProvider.

Built on $(StravaigBuildTime).
Build run details at: $(StravaigWorkflowUrl)
Release notes at: $(StravaigReleaseNotes)
      </Description>
      <rootnamespace>Stravaig.MonotonicClock</rootnamespace>
    </PropertyGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0' Or '$(TargetFramework)' == 'net8.0'">
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.19" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.11" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Stravaig.MonotonicClock\Stravaig.MonotonicClock.csproj" />
    </ItemGroup>

</Project>
